taquinsolver/cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

taquinsolver/taquin/urls.py
from django.urls import path

from . import views

app_name = 'taquin'
# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]
urlpatterns = [
    path('', views.index, name='index'),
    path('compute/', views.compute, name='compute')
]

taquinsolver/taquinsolver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('taquin/', include('taquin.urls')),
    path('cv', include('cv.urls')),
]

taquinsolver/cv/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

taquinsolver/cv/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'cv/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'cv/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'cv/results.html'

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'cv/index.html', context)

# # Leave the rest of the views (detail, results, vote) unchanged

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'cv/detail.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'cv/results.html', {'question': question})

def vote(request, question_id):
    import pdb; pdb.set_trace()
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'cv/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('cv:results', args=(question.id,)))

taquinsolver/taquin/views.py
from django.shortcuts import render
from django.template import loader
from django.http import JsonResponse

# Create your views here.

def index(request):
    return render(request, 'taquin/index.html')

def compute(request):
    initial = ['i-one', 'i-two', 'i-three', 'i-four', 'i-five', 'i-six', 'i-seven', 'i-eight', 'i-nine']
    target = ['t-one', 't-two', 't-three', 't-four', 't-five', 't-six', 't-seven', 't-eight', 't-nine']
    init_list = []
    target_list = []
    for i in initial:
        init_list.append(request.POST[i])
    for j in target:
        target_list.append(request.POST[j])
    print(target_list, init_list)
    return JsonResponse({'init': init_list, 'target': target_list})

taquinsolver/cv/templates/cv/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if question.choice_set.all %}
    <form action="{% url 'cv:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>
{% endif %}
<a href="{% url 'cv:index' %}">Go back</a>

taquinsolver/cv/templates/cv/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cv/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'cv:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

taquinsolver/cv/templates/cv/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'cv:detail' question.id %}">Vote again?</a>

taquinsolver/taquin/templates/taquin/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if question.choice_set.all %}
    <form action="{% url 'taquin:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>
{% endif %}
<a href="{% url 'taquin:index' %}">Go back</a>

taquinsolver/taquin/templates/taquin/index.html
<!DOCTYPE html>
<html lang="fr">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <title>My Resume</title>
        <link rel="stylesheet" type="text/css" href="{% static 'taquin/style.css' %}" />
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script src="https://unpkg.com/vue"></script>
    </head>
    <body>
        <div class="aside">ff</div>
        <div class="main">
            <div class="title-init">Initial Taquin</div>
            <div class="title-target">Target Taquin</div>
            <form name="taquins" class="taquins" action="compute/" method="post">{% csrf_token %}
                <fieldset name="taquin-initial" class="taquin-init">
                    <input type="text" class="taquin-elem" name="i-one" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-two" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-three" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-four" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-five" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-six" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-seven" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-eight" pattern="(X|[1-8])"/>
                    <input type="text" class="taquin-elem" name="i-nine" pattern="(X|[1-8])"/>
                </fieldset>
                <input type="submit" name="reset" value="Reset" class="button-reset" action="/compute" method="post">
                <fieldset name="taquin-final" class="taquin-target">
                    <input type="text" class="taquin-elem" name="t-one" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-two" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-three" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-four" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-five" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-six" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-seven" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-eight" pattern="(X|[1-8])">
                    <input type="text" class="taquin-elem" name="t-nine" pattern="(X|[1-8])">
                </fieldset>
                <input type="submit" name="submit" value="Submit" class="button-submit" action="/compute" method="post">             
            </form>
        </div>
        <div class="header">Taquin Solver</div>
        <script src="{% static 'taquin/myvue.js' %}"></script>        
    </body>
</html>





<!-- <body>
    <h1>Taquin Solver</h1>
    <div class="wrapper">
        <div class="taquin-headers" id="initial">Taquin initial</div>
        <div class="taquin-headers" id="final">Taquin final</div>
        <form id="taquin-solver" action="taquin/solve/" method="post" class="form-taquins">{% csrf_token %}
            <div class="taquin-initial">
                <input type="text" class="one" id="input-one" name="init-one" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="two" name="init-two" @blur="changeTextSize" @mouseover="changeColor" @mouseout="revertColor" @focus="$event.target.select()">
                <input type="text" class="three" name="init-three" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="four" name="init-four" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="five" name="init-five" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="six" name="init-six" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="seven" name="init-seven" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="eight" name="init-eight" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="nine" name="init-nine" @blur="changeTextSize" @focus="$event.target.select()">
            </div>
            <div class="taquin-final">
                <input type="text" class="one" id="output-one" name="init-one" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="two" name="output-two" @blur="changeTextSize" @mouseover="changeColor" @mouseout="revertColor" @focus="$event.target.select()">
                <input type="text" class="three" name="output-three" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="four" name="output-four" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="five" name="output-five" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="six" name="output-six" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="seven" name="output-seven" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="eight" name="output-eight" @blur="changeTextSize" @focus="$event.target.select()">
                <input type="text" class="nine" name="output-nine" @blur="changeTextSize" @focus="$event.target.select()">    
            </div>
            <div class="button">
                <button type="submit">Envoyer le message</button>
            </div>
        </form>
    </div>
</body>
<script src="{% static 'taquin/myvue.js' %}"></script>
</html> -->

taquinsolver/taquin/templates/taquin/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'taquin:detail' question.id %}">Vote again?</a>